"""
FastAPI WebSocket server for Twilio ConversationRelay.

Twilio handles STT (Deepgram) and TTS (ElevenLabs) natively.
We only exchange text over WebSocket — no audio processing needed.

Conversation responses are generated by GPT-4o-mini so each call
sounds natural, warm, and varied — never robotic or scripted.
The state machine handles *logic*; the LLM handles *words*.

Supports multi-service booking with 15-min break between services.
Recognizes returning patients by phone number.

Run: uvicorn voice_relay:app --host 0.0.0.0 --port 8001
"""

from __future__ import annotations

import json
import logging
import os
import random
from datetime import date as date_type, datetime, timedelta
from decimal import Decimal

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

import httpx
from asgiref.sync import sync_to_async
from fastapi import FastAPI, WebSocket, WebSocketDisconnect

from apps.clinic.models import Appointment, ClinicSettings, Patient, VoiceCallLog
from apps.clinic.public_booking_service import create_appointment_from_public_booking
from apps.clinic.serializers import PublicBookingSerializer
from apps.clinic.utils import normalize_phone
from apps.clinic.voice_ai import (
    _booking_catalog_json,
    _parse_time_12h,
    extract_name_from_speech,
    match_services_from_speech,
    openai_parse_datetime,
    parse_datetime_from_speech,
)
from apps.clinic.voice_logging import async_upsert_voice_call_log, upsert_voice_call_log

from django.conf import settings
from django.utils import timezone
from zoneinfo import ZoneInfo

# ORM helpers for async WebSocket handlers (Django forbids sync DB in async context).
_booking_catalog_async = sync_to_async(_booking_catalog_json, thread_sensitive=True)
_clinic_get_solo_async = sync_to_async(ClinicSettings.get_solo, thread_sensitive=True)
_openai_parse_datetime_async = sync_to_async(openai_parse_datetime, thread_sensitive=True)

logger = logging.getLogger("voice_relay")

app = FastAPI(title="ChiroFlow Voice Relay")

MAX_RETRIES = 5
BETWEEN_SERVICE_BUFFER_MINUTES = 15

# Shared async HTTP client for OpenAI calls (connection pooling)
_http_client: httpx.AsyncClient | None = None


async def _get_http_client() -> httpx.AsyncClient:
    global _http_client
    if _http_client is None or _http_client.is_closed:
        # Slightly longer default for voice (LLM + streaming reads).
        _http_client = httpx.AsyncClient(timeout=httpx.Timeout(45.0, connect=10.0))
    return _http_client


@app.on_event("shutdown")
async def _close_http_client():
    global _http_client
    if _http_client and not _http_client.is_closed:
        await _http_client.aclose()


# ─── LLM response generator ──────────────────────────────────────────

RECEPTIONIST_PERSONA = """\
You are Sarah, the front-desk receptionist at Relief Chiropractic. You love helping people feel \
welcome and you take real pride in getting their care scheduled smoothly. You're on a phone call \
with a patient or future patient.

TONE — JOVIAL YET PROFESSIONAL:
- Sound genuinely glad they called: bright, upbeat, and human — like a great front desk who \
enjoys their job. A touch of warmth and light enthusiasm is perfect.
- Stay professional for healthcare: respectful, clear, never flippant about health, pain, or \
scheduling. No slang that sounds teenage; no jokes at the patient's expense.
- Use natural contractions (you're, we'll, that's). Sprinkle in friendly phrases like \
"Wonderful!", "I'd be happy to help with that", "That's great", "Love it — let's get you booked", \
"Perfect timing" — but rotate; don't repeat the same opener every time.
- Vary your wording every reply so it never feels robotic or scripted.
- One short beat of rapport is fine (e.g. glad they chose the clinic, hope their day's going well) \
— then move the booking forward.
- Keep each reply SHORT: 1–3 sentences. Phone callers want quick, clear answers.

NEVER:
- Say you're an AI, bot, or automated system — you are Sarah at the desk.
- Invent services, prices, times, or policies not given in the instructions.

ALWAYS:
- Include every REQUIRED FACT from the instructions — names, dates, times, services, prices.
"""


async def _llm_respond(instruction: str, fallback: str) -> str:
    """Call GPT-4o-mini to generate a natural response. Falls back to static text."""
    api_key = getattr(settings, "OPENAI_API_KEY", "") or ""
    if not api_key.strip():
        return fallback

    model = getattr(settings, "OPENAI_VOICE_MODEL", None) or "gpt-5.4-nano"

    try:
        client = await _get_http_client()
        resp = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "temperature": 0.82,
                "max_tokens": 120,
                "messages": [
                    {"role": "system", "content": RECEPTIONIST_PERSONA},
                    {"role": "user", "content": instruction},
                ],
            },
        )
        resp.raise_for_status()
        data = resp.json()
        text = data["choices"][0]["message"]["content"].strip()
        text = text.strip('"').strip("'")
        return text if text else fallback
    except Exception:
        logger.exception("LLM response generation failed, using fallback")
        return fallback


async def _stream_openai_tokens_to_ws(ws: WebSocket, instruction: str, fallback: str) -> str:
    """
    Stream chat completion deltas to Twilio as they arrive (last=false), then one final last=true.
    Twilio recommends this over a single blob for lower latency to first audio.
    """
    api_key = (getattr(settings, "OPENAI_API_KEY", "") or "").strip()
    if not api_key:
        await _send_text(ws, fallback)
        return fallback

    model = getattr(settings, "OPENAI_VOICE_MODEL", None) or "gpt-5.4-nano"
    queued: str | None = None
    full_parts: list[str] = []

    try:
        client = await _get_http_client()
        async with client.stream(
            "POST",
            "https://api.openai.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "temperature": 0.82,
                "max_tokens": 120,
                "stream": True,
                "messages": [
                    {"role": "system", "content": RECEPTIONIST_PERSONA},
                    {"role": "user", "content": instruction},
                ],
            },
            timeout=httpx.Timeout(45.0, connect=10.0),
        ) as resp:
            resp.raise_for_status()
            async for line in resp.aiter_lines():
                if not line.startswith("data: "):
                    continue
                data = line[6:].strip()
                if data == "[DONE]":
                    break
                try:
                    obj = json.loads(data)
                except json.JSONDecodeError:
                    continue
                choices = obj.get("choices") or []
                if not choices:
                    continue
                delta = (choices[0].get("delta") or {})
                content = delta.get("content") or ""
                if not content:
                    continue
                full_parts.append(content)
                if queued is not None:
                    await ws.send_json({"type": "text", "token": queued, "last": False})
                queued = content

        if queued is not None:
            await ws.send_json({"type": "text", "token": queued, "last": True})
        full = "".join(full_parts).strip().strip('"').strip("'")
        if not full:
            await _send_text(ws, fallback)
            return fallback
        _last_responses[id(ws)] = full
        return full
    except Exception:
        logger.exception("OpenAI streaming failed, using fallback")
        await _send_text(ws, fallback)
        return fallback


async def _speak_llm(ws: WebSocket, instruction: str, fallback: str) -> str:
    """Generate Sarah's line: stream to Twilio when VOICE_LLM_STREAM is on, else one round-trip."""
    if getattr(settings, "VOICE_LLM_STREAM", True) and (getattr(settings, "OPENAI_API_KEY", "") or "").strip():
        return await _stream_openai_tokens_to_ws(ws, instruction, fallback)
    text = await _llm_respond(instruction, fallback)
    await _send_text(ws, text)
    return text


async def _end_session_speaking_llm(ws: WebSocket, instruction: str, fallback: str):
    await _speak_llm(ws, instruction, fallback)
    await ws.send_json({"type": "end"})


# ─── Helpers ──────────────────────────────────────────────────────────

def _svc_list(catalog: dict) -> str:
    svcs = catalog.get("services") or []
    chiro = [s["name"] for s in svcs if s.get("service_type") == "chiropractic"]
    mass = [s["name"] for s in svcs if s.get("service_type") == "massage"]
    parts = []
    if chiro:
        parts.append("Chiropractic: " + ", ".join(chiro))
    if mass:
        parts.append("Massage: " + ", ".join(mass))
    return ". ".join(parts) if parts else ", ".join(s["name"] for s in svcs)


def _svc_names(services: list[dict]) -> str:
    names = [s["name"] for s in services]
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f"{names[0]} and {names[1]}"
    return ", ".join(names[:-1]) + f", and {names[-1]}"


# Track last response for "repeat" support
_last_responses: dict[str, str] = {}


async def _send_text(ws: WebSocket, text: str, *, last: bool = True):
    await ws.send_json({
        "type": "text",
        "token": text,
        "last": last,
    })
    # Store for repeat — keyed by ws id
    _last_responses[id(ws)] = text


async def _end_session(ws: WebSocket, text: str = ""):
    if text:
        await _send_text(ws, text, last=True)
    await ws.send_json({"type": "end"})


# ─── Service entry ────────────────────────────────────────────────────

class ServiceEntry:
    def __init__(self, svc: dict, provider_id: int | None = None, provider_name: str = ""):
        self.service_id: int = svc["id"]
        self.service_name: str = svc["name"]
        self.service_duration: int = svc["duration_minutes"]
        self.service_price: str = svc["price"]
        self.provider_id: int | None = provider_id
        self.provider_name: str = provider_name
        self.appointment_date: str = ""
        self.start_time: str = ""
        self.booked_appt = None


# ─── Conversation state ──────────────────────────────────────────────

class ConversationState:
    def __init__(self, call_sid: str, from_number: str):
        self.call_sid = call_sid
        self.from_number = from_number
        self.step = "name"
        self.retries = 0
        self.first_name = ""
        self.last_name = ""
        self.catalog: dict | None = None
        self.is_returning = False

        self.services: list[ServiceEntry] = []
        self.current_svc_idx: int = 0
        self.pending_categories: list[str] = []
        self.last_service_id: int | None = None  # from appointment history

    @property
    def current_service(self) -> ServiceEntry | None:
        if 0 <= self.current_svc_idx < len(self.services):
            return self.services[self.current_svc_idx]
        return None

    @property
    def is_multi(self) -> bool:
        return len(self.services) > 1

    @property
    def has_more_services(self) -> bool:
        return self.current_svc_idx < len(self.services) - 1

    @property
    def caller_name(self) -> str:
        return f"{self.first_name} {self.last_name}".strip()


# ─── Patient lookup ──────────────────────────────────────────────────

def _lookup_patient(from_number: str) -> Patient | None:
    if not from_number:
        return None
    normalized = normalize_phone(from_number)
    if not normalized:
        return None
    try:
        return Patient.objects.get(phone=normalized)
    except Patient.DoesNotExist:
        return None
    except Patient.MultipleObjectsReturned:
        return Patient.objects.filter(phone=normalized).first()


def _returning_patient_voice_setup(from_number: str) -> dict | None:
    """Load returning-patient context from DB (sync only). Returns None if unknown caller."""
    patient = _lookup_patient(from_number)
    if not patient:
        return None
    catalog = _booking_catalog_json()
    last_sid = None
    last_appt = (
        Appointment.objects.filter(patient=patient)
        .exclude(
            status__in=[
                Appointment.Status.CANCELLED,
                Appointment.Status.NO_SHOW,
            ],
        )
        .order_by("-appointment_date")
        .first()
    )
    if last_appt and last_appt.booked_service_id:
        last_sid = last_appt.booked_service_id
    return {
        "first_name": patient.first_name,
        "last_name": patient.last_name,
        "catalog": catalog,
        "last_service_id": last_sid,
    }


_returning_setup_async = sync_to_async(_returning_patient_voice_setup, thread_sensitive=True)


# ─── Off-script intent detection ──────────────────────────────────────

_HOURS_PATTERNS = [
    "what are your hours", "when are you open", "what time do you open",
    "what time do you close", "are you open", "hours of operation",
    "business hours", "opening hours", "when do you close",
]
_PRICE_PATTERNS = [
    "how much", "what does it cost", "what's the price", "what is the price",
    "pricing", "cost of", "price of", "how much does",
]
_CANCEL_PATTERNS = [
    "cancel", "reschedule", "change my appointment", "move my appointment",
]
_TRANSFER_PATTERNS = [
    "talk to a person", "speak to someone", "real person", "human",
    "front desk", "receptionist", "operator", "talk to someone",
    "speak to a person", "actual person", "transfer me",
]
_REPEAT_PATTERNS = [
    "repeat that", "say that again", "what did you say", "can you repeat",
    "come again", "say again", "i didn't hear", "didn't catch that",
    "one more time", "pardon",
]


async def _handle_off_script(ws: WebSocket, state: ConversationState, speech: str) -> bool:
    """Check for off-script intents. Returns True if handled (caller stays on line)."""
    lower = speech.lower().strip()

    # Repeat last response
    if any(p in lower for p in _REPEAT_PATTERNS):
        last = _last_responses.get(id(ws), "")
        if last:
            await _send_text(ws, last)
        else:
            await _send_text(ws, "Sure! Go ahead, I'm listening.")
        return True

    # Transfer to human
    if any(p in lower for p in _TRANSFER_PATTERNS):
        await _end_session_speaking_llm(
            ws,
            "The caller wants to speak to a real person. Say something warm like "
            "'Absolutely, let me connect you to the front desk.' Then end the session.",
            "Of course! Let me transfer you to our front desk right now. One moment!",
        )
        return True

    # Business hours
    if any(p in lower for p in _HOURS_PATTERNS):
        clinic = await _clinic_get_solo_async()
        hours_info = ""
        if clinic.business_hours:
            try:
                bh = json.loads(clinic.business_hours) if isinstance(clinic.business_hours, str) else clinic.business_hours
                parts = []
                for day, times in bh.items():
                    if times:
                        parts.append(f"{day}: {times}")
                hours_info = "; ".join(parts) if parts else "Monday to Friday, 9 AM to 6 PM"
            except Exception:
                hours_info = "Monday to Friday, 9 AM to 6 PM"
        else:
            hours_info = "Monday to Friday, 9 AM to 6 PM"
        await _speak_llm(
            ws,
            f"The caller asked about business hours. Answer them, then bring them back to booking. "
            f"REQUIRED FACTS — hours: {hours_info}. Current step: {state.step}.",
            f"Our hours are {hours_info}. Now, would you like to go ahead and book an appointment?",
        )
        return True

    # Pricing
    if any(p in lower for p in _PRICE_PATTERNS):
        catalog = state.catalog or (await _booking_catalog_async())
        svcs = catalog.get("services") or []
        price_list = ", ".join(f"{s['name']}: ${s['price']} ({s['duration_minutes']} min)" for s in svcs)
        await _speak_llm(
            ws,
            f"The caller asked about pricing. Tell them the prices, then guide back to booking. "
            f"REQUIRED FACTS — {price_list}.",
            f"Here are our prices: {price_list}. Would you like to book one of these?",
        )
        return True

    # Cancel / reschedule
    if any(p in lower for p in _CANCEL_PATTERNS):
        await _speak_llm(
            ws,
            "The caller wants to cancel or reschedule. Let them know they can call the front desk "
            "or visit the website for that. Offer to book a new appointment if they want.",
            "For cancellations or rescheduling, you can call our front desk directly or visit our website. "
            "Would you like to book a new appointment instead?",
        )
        return True

    return False


# ─── Slot suggestions ─────────────────────────────────────────────────

def _find_nearby_slots(
    provider_id: int | None,
    service_id: int,
    appt_date: date_type,
    rejected_time,
    max_suggestions: int = 3,
) -> list[str]:
    """Find the nearest available slots to a rejected time on the same date."""
    from apps.clinic.models import Provider, Service
    from apps.clinic.booking_availability import provider_interval_blocked_online
    from datetime import time as time_cls

    if not provider_id:
        return []
    provider = Provider.objects.filter(pk=provider_id, active=True).first()
    service = Service.objects.filter(pk=service_id, is_active=True).first()
    if not provider or not service:
        return []

    duration = service.duration_minutes
    slot_step = 15 if service.service_type == "chiropractic" else max(duration, 15)
    day_start, day_end = 9 * 60, 18 * 60

    taken = set()
    for s, e in (
        Appointment.objects.filter(provider=provider, appointment_date=appt_date)
        .exclude(status__in=[
            Appointment.Status.CANCELLED, Appointment.Status.NO_SHOW,
            Appointment.Status.COMPLETED,
        ])
        .values_list("start_time", "end_time")
    ):
        for m in range(s.hour * 60 + s.minute, e.hour * 60 + e.minute):
            taken.add(m)

    slots: list[tuple[int, str]] = []
    cursor = day_start
    target_min = rejected_time.hour * 60 + rejected_time.minute if rejected_time else 600
    while cursor + duration <= day_end:
        if not any(cursor <= t < cursor + duration for t in taken):
            h, m = divmod(cursor, 60)
            st = time_cls(hour=h, minute=m)
            et_total = cursor + duration
            eh, em = divmod(et_total, 60)
            et = time_cls(hour=min(eh, 23), minute=em if eh < 24 else 59)
            if not provider_interval_blocked_online(provider.pk, appt_date, st, et):
                suffix = "AM" if h < 12 else "PM"
                dh = h if 1 <= h <= 12 else (h - 12 if h > 12 else 12)
                label = f"{dh}:{m:02d} {suffix}"
                slots.append((abs(cursor - target_min), label))
        cursor += slot_step

    slots.sort(key=lambda x: x[0])
    return [label for _, label in slots[:max_suggestions]]


_find_nearby_slots_async = sync_to_async(_find_nearby_slots, thread_sensitive=True)


# ─── Step handlers ────────────────────────────────────────────────────

async def handle_name(ws: WebSocket, state: ConversationState, speech: str):
    fn, ln = extract_name_from_speech(speech)

    if not fn and speech.strip():
        words = speech.strip().split()
        fn = words[0].title()
        ln = " ".join(words[1:]).title() if len(words) > 1 else ""

    logger.info("Voice [%s] name: %r %r", state.call_sid[:8], fn, ln)

    if not fn:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES, detail="name",
            )
            await _end_session_speaking_llm(
                ws,
                "The caller has been silent or unintelligible multiple times. "
                "Politely say goodbye and suggest they book online or call back later. "
                "Be empathetic, not frustrated.",
                "I'm having trouble hearing you. Please call back or book online at our website. Goodbye!",
            )
            return
        await _speak_llm(
            ws,
            "You couldn't hear the caller's name clearly. "
            "Ask them to repeat it naturally — don't sound robotic. "
            "Maybe say something like 'I didn't quite catch that' or 'sorry, could you say that again?'",
            "Sorry, I didn't quite catch your name. Could you say it one more time for me?",
        )
        return

    state.first_name = fn
    state.last_name = ln
    state.step = "service"
    state.retries = 0
    state.catalog = await _booking_catalog_async()

    services = _svc_list(state.catalog)
    await _speak_llm(
        ws,
        f"The caller's name is {fn} {ln}. Greet them warmly by name. "
        f"Then ask what service they'd like. Mention they can book more than one. "
        f"REQUIRED FACTS — available services: {services}",
        f"Great to meet you, {fn}! We offer: {services}. Which one would you like? You can also book more than one.",
    )


_SAME_AGAIN_PHRASES = [
    "same thing", "same one", "same service", "that again", "same as last",
    "the usual", "same as before", "like last time", "again please", "same please",
    "book that again", "the same", "do that again",
]


async def handle_service(ws: WebSocket, state: ConversationState, speech: str):
    catalog = state.catalog or (await _booking_catalog_async())
    all_services = catalog.get("services") or []
    pbs = catalog.get("providers_by_service") or {}

    # Returning patient saying "same thing" / "that again" — match last service
    if state.is_returning and state.last_service_id:
        lower = speech.lower().strip()
        is_yes, _ = _detect_yes_no(speech)
        if is_yes or any(p in lower for p in _SAME_AGAIN_PHRASES):
            last_svc = next((s for s in all_services if s["id"] == state.last_service_id), None)
            if last_svc:
                matched = [last_svc]
                # Skip normal matching and go straight to resolved
                state.retries = 0
                resolved = matched
                state.services = []
                for svc in resolved:
                    providers = pbs.get(svc["id"]) or []
                    pid = providers[0]["id"] if providers else None
                    pname = providers[0]["provider_name"] if providers else ""
                    state.services.append(ServiceEntry(svc, pid, pname))
                state.current_svc_idx = 0
                await _finish_service_selection(ws, state)
                return

    matched = match_services_from_speech(speech, all_services)

    if not matched:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES,
                detail=f"service: {speech}",
            )
            await _end_session_speaking_llm(
                ws,
                "The caller keeps requesting something you can't identify as a service. "
                "Apologize naturally, suggest they book online, and say goodbye warmly.",
                "I'm sorry, I'm not able to find that service. You can always book on our website. Thanks for calling!",
            )
            return
        svc_list = _svc_list(catalog)
        await _speak_llm(
            ws,
            f"The caller said something you couldn't match to a service. "
            f"They said: \"{speech}\". Apologize naturally and list the available services. "
            f"REQUIRED FACTS — available services: {svc_list}",
            f"Hmm, I didn't quite catch which service. We have: {svc_list}. Which sounds good?",
        )
        return

    state.retries = 0

    resolved: list[dict] = []
    pending: list[str] = []

    for svc in matched:
        stype = svc.get("service_type", "")
        same_type = [s for s in all_services if s.get("service_type") == stype]
        if len(same_type) > 1 and _was_category_match(speech, svc, same_type):
            if stype not in pending:
                pending.append(stype)
        else:
            resolved.append(svc)

    state.services = []
    for svc in resolved:
        providers = pbs.get(svc["id"]) or []
        pid = providers[0]["id"] if providers else None
        pname = providers[0]["provider_name"] if providers else ""
        state.services.append(ServiceEntry(svc, pid, pname))

    if pending:
        state.pending_categories = pending
        state.step = "pick_service"
        state.retries = 0
        cat = pending[0]
        cat_services = [s for s in all_services if s.get("service_type") == cat]
        names = ", ".join(s["name"] for s in cat_services)
        label = "chiropractic" if cat == "chiropractic" else "massage"
        await _speak_llm(
            ws,
            f"The caller wants {label} but there are multiple {label} options: {names}. "
            f"Ask which specific one they'd like. Be conversational about it. "
            f"REQUIRED FACTS — options: {names}",
            f"For {label}, we actually have a few options: {names}. Which one sounds right for you?",
        )
        return

    state.current_svc_idx = 0
    await _finish_service_selection(ws, state)


def _was_category_match(speech: str, matched_svc: dict, same_type_svcs: list[dict]) -> bool:
    import re
    s = speech.lower().strip()
    s = re.sub(r"^(i('d| would) like|i want|can i get|let's do)\s+", "", s).strip()
    s = re.sub(r"\b(a|an|the|both|and|also|please|thanks)\b", "", s).strip()
    s = re.sub(r"\s+", " ", s).strip()
    name_low = matched_svc["name"].lower()
    if name_low in s or s in name_low:
        return False
    for svc in same_type_svcs:
        if svc["name"].lower() in s:
            return False
    return True


async def _finish_service_selection(ws: WebSocket, state: ConversationState):
    if state.is_multi:
        state.step = "confirm_services"
        names = _svc_names([{"name": s.service_name} for s in state.services])
        await _speak_llm(
            ws,
            f"The caller selected multiple services: {names}. "
            f"Confirm with them naturally — like 'so you want both X and Y, right?' "
            f"REQUIRED FACTS — selected services: {names}",
            f"So you'd like both {names} — is that right?",
        )
    else:
        svc = state.services[0]
        state.step = "datetime"
        await _speak_llm(
            ws,
            f"The caller chose {svc.service_name} ({svc.service_duration} min, ${svc.service_price}). "
            f"Acknowledge their choice positively and ask what date and time works for them. "
            f"REQUIRED FACTS — service: {svc.service_name}",
            f"Great choice! {svc.service_name} it is. What date and time work best for you?",
        )


async def handle_pick_service(ws: WebSocket, state: ConversationState, speech: str):
    catalog = state.catalog or (await _booking_catalog_async())
    all_services = catalog.get("services") or []
    pbs = catalog.get("providers_by_service") or {}

    if not state.pending_categories:
        state.step = "service"
        await _send_text(ws, "Which service would you like?")
        return

    current_cat = state.pending_categories[0]
    cat_services = [s for s in all_services if s.get("service_type") == current_cat]

    from apps.clinic.voice_ai import match_service_from_speech
    picked = match_service_from_speech(speech, cat_services)

    if not picked:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES,
                detail=f"pick_service ({current_cat}): {speech}",
            )
            await _end_session(ws, "No worries at all — you can always book on our website. Thanks for calling!")
            return
        names = ", ".join(s["name"] for s in cat_services)
        await _speak_llm(
            ws,
            f"The caller tried to pick a specific {current_cat} service but you couldn't match it. "
            f"They said: \"{speech}\". Ask again naturally. "
            f"REQUIRED FACTS — options: {names}",
            f"I didn't quite get which one. We have: {names}. Which would you prefer?",
        )
        return

    state.retries = 0
    providers = pbs.get(picked["id"]) or []
    pid = providers[0]["id"] if providers else None
    pname = providers[0]["provider_name"] if providers else ""
    state.services.append(ServiceEntry(picked, pid, pname))

    state.pending_categories.pop(0)

    if state.pending_categories:
        next_cat = state.pending_categories[0]
        next_svcs = [s for s in all_services if s.get("service_type") == next_cat]
        names = ", ".join(s["name"] for s in next_svcs)
        label = "chiropractic" if next_cat == "chiropractic" else "massage"
        await _speak_llm(
            ws,
            f"Great, they picked {picked['name']}. Now ask about their {label} preference. "
            f"REQUIRED FACTS — options: {names}",
            f"Got it! And for {label}, we have: {names}. Which one?",
        )
        return

    state.current_svc_idx = 0
    await _finish_service_selection(ws, state)


import re as _re

# Compound phrases checked first — order matters
_NO_PHRASES = [
    "not right", "not correct", "that's wrong", "thats wrong",
    "no way", "don't think so", "i don't think so",
    "i'd rather not", "not really", "no thanks", "no thank you",
    "start over", "never mind", "nevermind",
]
_YES_PHRASES = [
    "go ahead", "book it", "sounds good", "yes please", "that works",
    "that's right", "thats right", "that's correct", "thats correct",
    "let's do it", "do it", "for sure",
]

_YES_WORD_SET = {
    "yes", "yeah", "yep", "yup", "correct", "right", "sure", "ok", "okay",
    "confirm", "please", "absolutely", "perfect", "yea", "affirmative",
}
_NO_WORD_SET = {
    "no", "nope", "nah", "wrong", "cancel", "incorrect", "change",
}


def _detect_yes_no(speech: str) -> tuple[bool, bool]:
    """Return (is_yes, is_no) using phrase priority then word-boundary matching."""
    lower = speech.lower().strip()

    # Phrase matching takes priority
    for phrase in _NO_PHRASES:
        if phrase in lower:
            return False, True
    for phrase in _YES_PHRASES:
        if phrase in lower:
            return True, False

    # Word-boundary matching (avoids "right" inside "not right", etc.)
    words = set(_re.findall(r"\b\w+(?:'\w+)?\b", lower))
    is_yes = bool(words & _YES_WORD_SET)
    is_no = bool(words & _NO_WORD_SET)
    return is_yes, is_no


async def handle_confirm_services(ws: WebSocket, state: ConversationState, speech: str):
    is_yes, is_no = _detect_yes_no(speech)

    if is_no and not is_yes:
        state.step = "service"
        state.retries = 0
        state.services = []
        await _speak_llm(
            ws,
            "The caller changed their mind about the services. "
            "Be understanding and ask what they'd like instead. Keep it casual.",
            "No problem at all! What service would you like instead?",
        )
        return

    if not is_yes:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES, detail="confirm_services",
            )
            await _end_session(ws, "No worries, you can book on our website anytime. Thanks for calling!")
            return
        names = _svc_names([{"name": s.service_name} for s in state.services])
        await _speak_llm(
            ws,
            f"The caller's response was unclear. You need a yes or no about booking {names}. "
            f"Ask again in a friendly way. REQUIRED FACTS — services: {names}",
            f"Just checking — did you want both {names}? Just say yes or no.",
        )
        return

    state.step = "datetime"
    state.retries = 0
    svc = state.current_service
    if state.is_multi:
        await _speak_llm(
            ws,
            f"The caller confirmed they want both services. Now ask about date and time. "
            f"Mention you'll start scheduling with {svc.service_name}. "
            f"REQUIRED FACTS — first service: {svc.service_name}",
            f"Awesome! Let's get those scheduled. Starting with {svc.service_name} — what date and time work for you?",
        )
    else:
        await _speak_llm(
            ws,
            "The caller confirmed the service. Ask what date and time works for them. Be upbeat.",
            "Perfect! What date and time work best for you?",
        )


async def handle_datetime(ws: WebSocket, state: ConversationState, speech: str):
    tz_name = getattr(settings, "CLINIC_TIMEZONE", "America/Detroit")
    today = timezone.now().astimezone(ZoneInfo(tz_name)).date()

    appt_date, start_time = parse_datetime_from_speech(speech, today)

    if not appt_date or not start_time:
        ai_date, ai_time = await _openai_parse_datetime_async(speech, today.isoformat())
        appt_date = appt_date or ai_date
        start_time = start_time or ai_time

    if not appt_date or not start_time:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES,
                detail=f"datetime: {speech}",
            )
            await _end_session_speaking_llm(
                ws,
                "You've tried multiple times to understand the date/time but can't. "
                "Apologize, suggest booking online, and say goodbye warmly.",
                "I'm really sorry about this — I'm having trouble with the date. "
                "You can always book on our website anytime. Thanks for calling!",
            )
            return

        if not appt_date and not start_time:
            hint = "neither the date nor time"
        elif not appt_date:
            hint = "the time but not the date"
        else:
            hint = "the date but not the time"
        await _speak_llm(
            ws,
            f"The caller said \"{speech}\" for date/time but you only caught {hint}. "
            f"Ask them to clarify naturally. Give an example like 'next Tuesday at 2 PM'. "
            f"Don't be robotic about it.",
            "I didn't quite get that. Could you say something like 'next Tuesday at 2 PM'?",
        )
        return

    svc = state.current_service
    svc.appointment_date = appt_date
    svc.start_time = start_time
    state.step = "confirm"
    state.retries = 0

    try:
        d = date_type.fromisoformat(appt_date)
        dd = d.strftime("%A, %B %d")
    except ValueError:
        dd = appt_date
    t = _parse_time_12h(start_time)
    td = t.strftime("%I:%M %p") if t else start_time
    name = state.caller_name

    if state.is_multi and state.has_more_services:
        next_svc = state.services[state.current_svc_idx + 1]
        end_t = _add_minutes(t, svc.service_duration) if t else None
        next_start = _add_minutes(end_t, BETWEEN_SERVICE_BUFFER_MINUTES) if end_t else None
        next_td = next_start.strftime("%I:%M %p") if next_start else "after a short break"
        await _speak_llm(
            ws,
            f"Confirm multi-service booking with {name}. "
            f"REQUIRED FACTS you MUST include: "
            f"1) {svc.service_name} on {dd} at {td}. "
            f"2) Then a 15-minute break. "
            f"3) Then {next_svc.service_name} at {next_td}. "
            f"Ask if that sounds good. Be natural.",
            f"Alright {name}, so here's the plan: {svc.service_name} on {dd} at {td}, "
            f"then a little 15-minute break, and {next_svc.service_name} at {next_td}. "
            f"Does that work for you?",
        )
    else:
        await _speak_llm(
            ws,
            f"Confirm a single appointment with {name}. "
            f"REQUIRED FACTS you MUST include: "
            f"{svc.service_name} on {dd} at {td}. "
            f"Ask if that's good. Keep it natural and brief.",
            f"Perfect, {name}! So that's {svc.service_name} on {dd} at {td}. Shall I lock that in?",
        )


def _add_minutes(t, minutes: int):
    if not t:
        return None
    dt = datetime.combine(date_type.today(), t) + timedelta(minutes=minutes)
    return dt.time()


async def handle_confirm(ws: WebSocket, state: ConversationState, speech: str):
    is_yes, is_no = _detect_yes_no(speech)

    if is_no and not is_yes:
        svc = state.current_service
        svc.appointment_date = ""
        svc.start_time = ""
        state.step = "datetime"
        state.retries = 0
        await _speak_llm(
            ws,
            "The caller wants to change the date/time. "
            "Be understanding and ask for a new date and time. Keep it light.",
            "No problem! What other date and time would work better for you?",
        )
        return

    if not is_yes:
        state.retries += 1
        if state.retries >= MAX_RETRIES:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid, from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.ABANDONED_RETRIES, detail="confirm",
            )
            await _end_session(ws, "No worries, you can book on our website anytime. Thanks for calling!")
            return
        await _speak_llm(
            ws,
            "The caller's response was unclear — you need a yes or no to book the appointment. "
            "Ask again naturally, not robotically.",
            "Just want to make sure — should I go ahead and book that for you?",
        )
        return

    await do_book_all(ws, state)


# ─── Booking logic ────────────────────────────────────────────────────

async def do_book_all(ws: WebSocket, state: ConversationState):
    phone = state.from_number
    if phone.startswith("tel:"):
        phone = phone[4:]

    booked: list[tuple[str, str, str]] = []
    last_end_time = None
    last_date = None

    for idx in range(state.current_svc_idx, len(state.services)):
        svc = state.services[idx]
        state.current_svc_idx = idx

        if idx > 0 and not svc.appointment_date and last_date and last_end_time:
            svc.appointment_date = last_date
            buffer_start = _add_minutes(last_end_time, BETWEEN_SERVICE_BUFFER_MINUTES)
            svc.start_time = buffer_start.strftime("%I:%M %p")

        result = await _book_single(ws, state, svc, phone)
        if result is None:
            # Partial failure: some services already booked
            if booked:
                already = " and ".join(f"{n} on {d} at {t}" for n, d, t in booked)
                await _speak_llm(
                    ws,
                    f"The first appointment was booked successfully ({already}), but "
                    f"the next one ({svc.service_name}) couldn't be booked at that time. "
                    f"Let the caller know the first is confirmed, and ask for a new "
                    f"date/time for the remaining service. Be reassuring. "
                    f"REQUIRED FACTS: {already} is confirmed.",
                    f"Good news — your {booked[0][0]} is confirmed for {booked[0][1]} at {booked[0][2]}! "
                    f"But the slot for {svc.service_name} isn't available. "
                    f"What other time would work for that one?",
                )
            return

        appt, td, dd = result
        svc.booked_appt = appt
        booked.append((svc.service_name, dd, td))

        last_date = svc.appointment_date
        t = _parse_time_12h(svc.start_time)
        if t:
            last_end_time = _add_minutes(t, svc.service_duration)

    await _build_final_message(ws, state, booked)


def _book_single_try_sync(
    payload: dict,
    *,
    call_sid: str,
    from_number: str,
    transcript: str,
) -> tuple[str, object | None]:
    """Run serializer + booking in one sync DB transaction context. Returns ('ok', appt) or error tag."""
    ser = PublicBookingSerializer(data=payload)
    if not ser.is_valid():
        logger.info("Voice serializer errors: %s", ser.errors)
        upsert_voice_call_log(
            call_sid=call_sid,
            from_number=from_number,
            transcript=transcript,
            outcome=VoiceCallLog.Outcome.SERIALIZER_REJECTED,
            detail=str(ser.errors)[:2000],
        )
        return "serializer", None
    appt, err = create_appointment_from_public_booking(ser.validated_data)
    if err:
        logger.info("Voice booking error: %s", err)
        upsert_voice_call_log(
            call_sid=call_sid,
            from_number=from_number,
            transcript=transcript,
            outcome=VoiceCallLog.Outcome.SLOT_OR_RULE_ERROR,
            detail=err[:2000],
        )
        return "slot", None
    upsert_voice_call_log(
        call_sid=call_sid,
        from_number=from_number,
        transcript=transcript,
        outcome=VoiceCallLog.Outcome.BOOKED,
        appointment=appt,
    )
    return "ok", appt


_book_single_try_async = sync_to_async(_book_single_try_sync, thread_sensitive=True)


async def _book_single(
    ws: WebSocket, state: ConversationState, svc: ServiceEntry, phone: str
) -> tuple | None:
    try:
        appt_date = date_type.fromisoformat(svc.appointment_date)
    except (ValueError, KeyError):
        state.step = "datetime"
        state.retries = 0
        await _speak_llm(
            ws,
            "Something went wrong with the date internally. "
            "Ask the caller to say the date and time again. Sound apologetic but casual.",
            "Sorry about that — could you give me the date and time one more time?",
        )
        return None

    t = _parse_time_12h(svc.start_time)
    if not t:
        state.step = "datetime"
        state.retries = 0
        await _speak_llm(
            ws,
            "Something went wrong with the time internally. "
            "Ask the caller to repeat the date and time. Sound apologetic.",
            "Sorry, I had a hiccup with the time. Could you say it again for me?",
        )
        return None

    payload = {
        "first_name": state.first_name[:100],
        "last_name": state.last_name[:100],
        "phone": phone,
        "email": "",
        "service_id": svc.service_id,
        "service_duration_minutes": int(svc.service_duration),
        "service_price": Decimal(str(svc.service_price)),
        "appointment_date": appt_date,
        "start_time": t,
    }
    if svc.provider_id:
        payload["provider_id"] = int(svc.provider_id)

    transcript = (
        f"Name: {state.first_name} {state.last_name}, "
        f"Service: {svc.service_name}, "
        f"Date: {svc.appointment_date}, Time: {svc.start_time}"
    )

    status, appt = await _book_single_try_async(
        payload,
        call_sid=state.call_sid,
        from_number=state.from_number,
        transcript=transcript,
    )
    if status == "serializer":
        await _offer_alternative_slots(ws, state, svc, t)
        return None
    if status == "slot":
        await _offer_alternative_slots(ws, state, svc, t)
        return None

    td = appt.start_time.strftime("%I:%M %p")
    dd = appt.appointment_date.strftime("%A, %B %d")
    return appt, td, dd


async def _offer_alternative_slots(ws, state, svc, rejected_time):
    """When a slot is rejected, find nearby alternatives and offer them."""
    svc.appointment_date_backup = svc.appointment_date
    svc.appointment_date = ""
    svc.start_time = ""
    state.step = "datetime"
    state.retries = 0

    try:
        appt_date = date_type.fromisoformat(svc.appointment_date_backup)
        nearby = await _find_nearby_slots_async(
            svc.provider_id, svc.service_id, appt_date, rejected_time
        )
    except Exception:
        nearby = []

    if nearby:
        slot_list = ", ".join(nearby[:3])
        await _speak_llm(
            ws,
            f"The requested time for {svc.service_name} is not available. "
            f"But you found these nearby open slots on the same day: {slot_list}. "
            f"Offer them naturally. The caller can also pick a totally different date. "
            f"REQUIRED FACTS — available slots: {slot_list}",
            f"That time's taken, but I have {slot_list} available. "
            f"Would any of those work, or would you prefer a different day?",
        )
    else:
        await _speak_llm(
            ws,
            f"The time for {svc.service_name} is taken and no other slots are available on that day. "
            f"Ask the caller to try a different date. Be empathetic.",
            f"Unfortunately that slot is taken and the rest of the day looks full. "
            f"Would you like to try a different date?",
        )


async def _build_final_message(ws: WebSocket, state: ConversationState, booked: list[tuple[str, str, str]]):
    name = state.caller_name
    if len(booked) == 1:
        svc_name, dd, td = booked[0]
        await _end_session_speaking_llm(
            ws,
            f"The appointment is confirmed! Tell {name} their booking details and say goodbye. "
            f"Be genuinely warm and excited for them. Mention they'll get a text and email. "
            f"REQUIRED FACTS: {svc_name} on {dd} at {td}. "
            f"Confirmation sent via text and email.",
            f"You're all set, {name}! Your {svc_name} is booked for {dd} at {td}. "
            "You'll get a text and email confirmation. Have an awesome day!",
        )
    else:
        details = "; ".join(f"{n} on {d} at {t}" for n, d, t in booked)
        await _end_session_speaking_llm(
            ws,
            f"Both appointments are confirmed for {name}! Tell them the details and say goodbye warmly. "
            f"Mention they'll get a text and email for each appointment. "
            f"REQUIRED FACTS: {details}.",
            f"You're all set, {name}! Both appointments are confirmed — "
            + " and ".join(f"{n} at {t}" for n, d, t in booked)
            + f" on {booked[0][1]}. "
            "You'll get confirmations for each by text and email. Have a wonderful day!",
        )


# ─── Step dispatcher ──────────────────────────────────────────────────

STEP_HANDLERS = {
    "name": handle_name,
    "service": handle_service,
    "pick_service": handle_pick_service,
    "confirm_services": handle_confirm_services,
    "datetime": handle_datetime,
    "confirm": handle_confirm,
}

# Nudge messages — these are also varied via LLM when possible
_NUDGE_CONTEXTS = {
    "name": "The caller has been silent. Gently ask for their first and last name again. Be patient.",
    "service": "The caller has been silent. Gently remind them of available services and ask what they'd like.",
    "pick_service": "The caller went silent while picking a specific service. Gently re-ask.",
    "confirm_services": "The caller went silent during service confirmation. Gently ask yes or no.",
    "datetime": "The caller went silent. Gently ask what date and time works for them.",
    "confirm": "The caller went silent during final confirmation. Gently ask if they'd like to book.",
}

_NUDGE_FALLBACKS = {
    "name": "I'm still here! Could you tell me your first and last name?",
    "service": "Still here! Which service would you like?",
    "pick_service": "Which specific option would you prefer?",
    "confirm_services": "Just say yes to confirm or no if you'd like to change anything.",
    "datetime": "What date and time work for you?",
    "confirm": "Should I go ahead and book that for you?",
}


# ─── WebSocket endpoint ──────────────────────────────────────────────

@app.websocket("/ws/voice")
async def voice_websocket(ws: WebSocket):
    await ws.accept()
    state: ConversationState | None = None

    try:
        while True:
            raw = await ws.receive_text()
            msg = json.loads(raw)
            msg_type = msg.get("type", "")

            if msg_type == "setup":
                call_sid = msg.get("callSid", "")
                from_number = msg.get("from", "")
                state = ConversationState(call_sid, from_number)

                await async_upsert_voice_call_log(
                    call_sid=call_sid,
                    from_number=from_number,
                    outcome=VoiceCallLog.Outcome.PROMPTED,
                )
                logger.info("Voice WS [%s] setup from %s", call_sid[:8], from_number)

                # Returning patient: TwiML greeting already welcomed them
                # and asked about services — just set up state silently
                returning = await _returning_setup_async(from_number)
                if returning:
                    state.first_name = returning["first_name"]
                    state.last_name = returning["last_name"]
                    state.step = "service"
                    state.is_returning = True
                    state.catalog = returning["catalog"]
                    if returning["last_service_id"]:
                        state.last_service_id = returning["last_service_id"]
                    logger.info(
                        "Voice WS [%s] returning patient: %s %s",
                        call_sid[:8], returning["first_name"], returning["last_name"],
                    )

            elif msg_type == "prompt":
                speech = msg.get("voicePrompt", "").strip()

                if not state:
                    logger.warning("Received prompt before setup, ignoring")
                    continue

                logger.info(
                    "Voice WS [%s] step=%s speech=%r",
                    state.call_sid[:8], state.step, speech[:120] if speech else "",
                )

                await async_upsert_voice_call_log(
                    call_sid=state.call_sid,
                    from_number=state.from_number,
                    transcript=speech,
                )

                if not speech:
                    state.retries += 1
                    if state.retries >= MAX_RETRIES:
                        await async_upsert_voice_call_log(
                            call_sid=state.call_sid,
                            from_number=state.from_number,
                            outcome=VoiceCallLog.Outcome.EMPTY_SPEECH,
                            detail="silence",
                        )
                        await _end_session_speaking_llm(
                            ws,
                            "The caller has been completely silent for a while. "
                            "Say goodbye gently — maybe they got disconnected. "
                            "Invite them to call back anytime.",
                            "Looks like we may have lost the connection. "
                            "Feel free to call back anytime. Take care!",
                        )
                        break

                    context = _NUDGE_CONTEXTS.get(state.step, "The caller is silent. Gently ask if they're still there.")
                    fallback = _NUDGE_FALLBACKS.get(state.step, "I'm here! Go ahead whenever you're ready.")
                    if getattr(settings, "VOICE_LLM_FOR_SILENCE_NUDGES", False):
                        await _speak_llm(ws, context, fallback)
                    else:
                        await _send_text(ws, fallback)
                    continue

                # Check for off-script intents before step handlers
                if await _handle_off_script(ws, state, speech):
                    continue

                state.retries = 0
                handler = STEP_HANDLERS.get(state.step, handle_name)
                await handler(ws, state, speech)

            elif msg_type == "interrupt":
                logger.info(
                    "Voice WS [%s] caller interrupted",
                    state.call_sid[:8] if state else "?",
                )

            elif msg_type == "dtmf":
                digit = msg.get("digit", "")
                logger.info(
                    "Voice WS [%s] DTMF: %s",
                    state.call_sid[:8] if state else "?",
                    digit,
                )
                if digit == "0":
                    # Transfer to front desk
                    await _end_session(
                        ws,
                        "Absolutely, let me connect you to our front desk. One moment!",
                    )
                elif digit == "*":
                    # Repeat last response
                    last = _last_responses.get(id(ws), "")
                    if last:
                        await _send_text(ws, last)
                    else:
                        await _send_text(ws, "I'm here! Go ahead whenever you're ready.")

            elif msg_type == "error":
                logger.error(
                    "Voice WS ConversationRelay error: %s",
                    msg.get("description", "unknown"),
                )

    except WebSocketDisconnect:
        _last_responses.pop(id(ws), None)
        if state:
            logger.info("Voice WS [%s] disconnected", state.call_sid[:8])
    except Exception:
        _last_responses.pop(id(ws), None)
        logger.exception("Voice WS unexpected error")
        if state:
            await async_upsert_voice_call_log(
                call_sid=state.call_sid,
                from_number=state.from_number,
                outcome=VoiceCallLog.Outcome.OPENAI_FAILED,
                detail="WebSocket error",
            )


# ─── Health check ─────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("VOICE_WS_PORT", "8001"))
    uvicorn.run(app, host="0.0.0.0", port=port)
