# Generated by Django 5.2.12 on 2026-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services this doctor offers for booking', related_name='providers', to='clinic.service'),
        ),
    ]
