# Generated by Django 5.2.12
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_add_provider_services_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("chiropractic", "Chiropractic"), ("massage", "Massage")],
                default="chiropractic",
                help_text="Chiropractic: one doctor assigned by admin, no choice. Massage: patient chooses from assigned providers.",
                max_length=20,
            ),
            preserve_default=True,
        ),
    ]
