# Generated by Django 5.2.12 on 2026-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_state_zip',
            field=models.CharField(blank=True, help_text='e.g. St Joseph, MI 49085', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='stripe_default_payment_method_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
