# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_patient_intake_stripe_visit_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="sms_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
