# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_appointment_sms_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="google_refresh_token",
            field=models.TextField(blank=True, help_text="OAuth refresh token for personal Google Calendar"),
        ),
        migrations.AddField(
            model_name="provider",
            name="google_calendar_id",
            field=models.CharField(
                blank=True,
                default="primary",
                help_text="Calendar id to write events to (default: primary)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
