# Generated by Django 5.2.12 on 2026-03-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_staffnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(default='Relief Chiropractic PC', max_length=200)),
                ('address_line1', models.CharField(default='3830 M 139, Suite 119', max_length=200)),
                ('city_state_zip', models.CharField(default='St Joseph, MI 49085', max_length=200)),
                ('phone', models.CharField(default='269-408-0303', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pos_default', models.CharField(default='11', help_text='Default place-of-service code on printed bill lines.', max_length=10)),
                ('business_hours', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Clinic settings',
            },
        ),
    ]
