# Generated by Django 5.2.12 on 2026-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_clinic_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='clinic_staf_recipie_0e6dc5_idx',
            old_name='clinic_staf_recipie_7e8a0f_idx',
        ),
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='clinic_staf_recipie_fbe6a9_idx',
            old_name='clinic_staf_recipie_8f1b2c_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_public_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='billing_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
