# Generated by Django 5.2.12 on 2026-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_rename_patient_stripe_to_square'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voicecalllog',
            new_name='clinic_voic_created_428605_idx',
            old_name='clinic_voicelog_created_at',
        ),
        migrations.RenameIndex(
            model_name='voicecalllog',
            new_name='clinic_voic_outcome_3764f9_idx',
            old_name='clinic_voicelog_outcome_created',
        ),
        migrations.AlterField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Visit types this doctor appears under on online booking. In-room billing uses the full clinic service list.', related_name='providers', to='clinic.service'),
        ),
    ]
