# Generated by Django 5.2.14 on 2026-07-29 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0051_appointment_late_checkin_sms_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientIntakeAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "form_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of form_type strings. Empty = auto-recommend.",
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_access_tokens",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_access_tokens",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientIntakeSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("massage", "Massage intake"),
                            ("pediatric", "Children / pediatric intake"),
                            ("adult_chiropractic", "Adult chiropractic new-patient paperwork"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("signature_name", models.CharField(blank=True, default="", max_length=200)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional appointment that triggered this form pack.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_submissions",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_submissions",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patientintakeaccesstoken",
            index=models.Index(fields=["patient_id", "expires_at"], name="intake_tok_pat_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="patientintakesubmission",
            index=models.Index(fields=["patient_id", "form_type", "status"], name="intake_sub_pat_type_st_idx"),
        ),
        migrations.AddIndex(
            model_name="patientintakesubmission",
            index=models.Index(fields=["status", "submitted_at"], name="intake_sub_status_sub_idx"),
        ),
    ]
