# Generated by Django 5.2.17 on 2026-08-25 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0056_rename_syserr_resolved_created_idx_clinic_syst_resolve_bd6693_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="auto_no_show_processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the system automatically marked this visit as no-show.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="clinical_handoff_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff/doctor reminders for this visit (birthday, preferences, handoff to next provider). Not the same as consultation SOAP notes on the Visit record.",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="no_show_notice_email_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="no_show_notice_sms_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="auto_no_show_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Automatically mark unattended visits as no-show after the grace period.",
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="auto_no_show_grace_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Minutes after scheduled start before auto no-show runs.",
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="no_show_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                help_text="Fallback no-show amount (USD) when the booked visit type has no price. Normally chiropractic and massage no-shows use the booked service price. Set to 0 to skip only that fallback. Card on file is charged when possible; otherwise the visit may stay in Awaiting payment.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("visit", "Visit"),
                    ("no_show_fee", "No-show fee"),
                    ("late_cancel_fee", "Late cancellation fee"),
                ],
                default="visit",
                help_text="Visit = normal clinical invoice; penalty kinds = missed visit or late cancellation per clinic policy.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_established",
            field=models.DateField(
                blank=True,
                help_text="Staff override for date established. When blank, the system uses the first non-cancelled appointment date.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="notify_bills",
            field=models.CharField(
                choices=[
                    ("sms", "Text (SMS) only"),
                    ("email", "Email only"),
                    ("both", "Text and email"),
                    ("none", "None"),
                ],
                default="email",
                help_text="Paid receipt / patient bill email from the portal. sms = text only, email = email only, both = both channels, none = no automated messages.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="notify_booking",
            field=models.CharField(
                choices=[
                    ("sms", "Text (SMS) only"),
                    ("email", "Email only"),
                    ("both", "Text and email"),
                    ("none", "None"),
                ],
                default="sms",
                help_text="Booking / reschedule / cancel confirmations. sms = text only, email = email only, both = both channels, none = no automated messages.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="notify_reminders",
            field=models.CharField(
                choices=[
                    ("sms", "Text (SMS) only"),
                    ("email", "Email only"),
                    ("both", "Text and email"),
                    ("none", "None"),
                ],
                default="sms",
                help_text="Day-before and same-day appointment reminders. SMS also requires SMS consent. sms = text only, email = email only, both = both channels, none = no automated messages.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="primary_service_type",
            field=models.CharField(
                choices=[("chiropractic", "Chiropractic"), ("massage", "Massage")],
                default="chiropractic",
                help_text="Default online booking category: chiropractic vs massage visit types.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Visit types this doctor appears under on online booking. In-room billing uses active services allowed for their role (see each service's staff visibility).",
                related_name="providers",
                to="clinic.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="visible_to_chiropractic_staff",
            field=models.BooleanField(
                default=True,
                help_text="If True, chiropractic doctors see this service when completing a visit.",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="visible_to_massage_staff",
            field=models.BooleanField(
                default=True,
                help_text="If True, massage therapists see this service when completing a visit.",
            ),
        ),
        migrations.AlterField(
            model_name="systemerrorlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("api", "API"),
                    ("middleware", "Middleware"),
                    ("celery", "Celery"),
                    ("client", "Browser (admin)"),
                    ("voice_ai", "Voice AI"),
                ],
                default="api",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voicecalllog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("prompted", "Greeting played"),
                    ("no_openai", "OpenAI not configured"),
                    ("empty_speech", "No speech detected"),
                    ("openai_failed", "Could not understand (AI)"),
                    ("intent_incomplete", "Missing name, service, or time"),
                    ("serializer_rejected", "Data did not validate"),
                    ("slot_or_rule_error", "Slot taken or not bookable"),
                    ("booked", "Appointment created"),
                    ("abandoned_retries", "Hung up after retries"),
                    ("disconnected", "Disconnected mid-call"),
                ],
                default="prompted",
                max_length=32,
            ),
        ),
    ]
